site_name: База знаний
site_url: https://kb.survey-studio.com
site_description: База знаний SurveyStudio
site_author: SIIS Ltd
copyright: <a href="https://siisltd.ru/">© SIIS Ltd 2021</a> | <a href="mailto:support@siisltd.ru">support@siisltd.ru</a>

nav:
  - 'Начало': 'index.md'
  - 'Обновления':
    - '2020.08': 'release_notes/2020.08.md'
    - '2020.07': 'release_notes/2020.07.md'
    - '2020.06': 'release_notes/2020.06.md'
    - '2020.05': 'release_notes/2020.05.md'
    - '2020.04': 'release_notes/2020.04.md'
    - '2020.03': 'release_notes/2020.03.md'
    - '2020.01': 'release_notes/2020.01.md'
    - '2019.12.19': 'release_notes/2019.12.19.md'
  - 'Описание системы':
    - 'Создание анкет':
      - 'Введение': 'help/1000.md'
      - 'Работа со списком анкет, добавление новой анкеты': 'help/1001.md'
      - 'Редактор вопросов анкеты': 'help/1002.md'
      - 'Свойства вопроса (редактирование вопроса) анкеты': 'help/1003.md'
      - 'Редактор списка вариантов ответа': 'help/1004.md'
      - 'Действия перед показом и после ответа на вопрос': 'help/1005.md'
      - 'Описание синтаксиса выражений': 'help/1006.md'
      - 'Выгрузка и загрузка анкеты, описание структуры файла с анкетой': 'help/1007.md'
      - 'Изменение оформления анкеты': 'help/1008.md'
    - 'Написание скриптов':
      - 'Введение': 'help/2000.md'
      - 'Глобальные объекты, функции и переменные': 'help/2001.md'
      - 'Свойства и функции вопроса': 'help/2002.md'
      - 'Свойства и функции ответа': 'help/2003.md'
      - 'Свойства и функции списка ответов': 'help/2004.md'
      - 'Свойства и функции строки табличного вопроса': 'help/2005.md'
      - 'Свойства и функции списка строк табличного вопроса': 'help/2006.md'
      - 'Свойства и функции колонки табличного вопроса': 'help/2007.md'
      - 'Свойства и функции списка колонок табличного вопроса': 'help/2008.md'
      - 'Сборник готовых скриптов': 'help/2999.md'
    - 'Работа с проектами':
      - 'Введение': 'help/3000.md'
      - 'Работа со списком проектов, добавление нового проекта': 'help/3001.md'
      - 'Статистика проекта': 'help/3002.md'
      - 'Счётчики и квоты': 'help/3003.md'
      - 'Базы контактов': 'help/3005.md'
      - 'Просмотр интервью': 'help/3009.md'
      - 'Выгрузка результатов': 'help/3004.md'
      - 'Выгрузка файлов': 'help/3008.md'
      - 'Редактирование ответов': 'help/3006.md'
      - 'Контроль интервью': 'help/3007.md'
      - 'Назначение подрядчиков': 'help/3010.md'
    - 'Пользователи и права доступа':
      - 'Введение': 'help/4000.md'
      - 'Работа со списком пользователей, добавление нового пользователя': 'help/4001.md'
      - 'Группы пользователей': 'help/4002.md'
      - 'Права доступа': 'help/4003.md'
    - 'DEX 1.x': 'help/9000.md'
    - 'DEX': 'help/5000.md'
    - 'Финансы': 'help/6000.md'
    - 'Профиль': 'help/7001.md'
  - 'Статьи':
    - 'Перенос выбранных ответов из одного вопроса с выбором в другой': 'articles/1013.md'
    - 'Использование приложения на планшете': 'articles/1012.md'
    - 'Делегирование прав подрядчику': 'articles/1011.md'
    - 'Автоматическая группировка баз контактов': 'articles/1010.md'    
    - 'Опрос по индивидуальным ссылкам': 'articles/1009.md'
    - 'Взаимодействие с онлайн панелью': 'articles/1008.md'
    - 'Опрос на планшете': 'articles/1007.md'
    - 'Счётчики, квоты и полные интервью': 'articles/1006.md'
    - 'Правила формирования имен переменных (колонок) в итоговом массиве': 'articles/1005.md'
    - 'Вертикальный текст в заголовке колонок табличных вопросов': 'articles/1004.md'
    - 'Ручной контроль правильности ответа на вопрос': 'articles/1003.md'
    - 'Показать в вопросе только те варианты ответа, которые отметили в предыдущем вопросе': 'articles/1002.md'
    - 'Подстановка в текст вопроса ответов из предыдущих вопросов': 'articles/1001.md'
    - 'Нюансы использования проверки на неравенство в выражениях': 'articles/1000.md'
  - 'Вопросы и ответы': 'faq.md'
  - 'Видео': 'video.md'
  - '← В личный кабинет': 'https://survey-studio.com/client'

theme:
  name: 'material'
  language: 'ru'
  favicon: 'images/favicon.ico'
  font:
    text: 'Segoe UI'
    code: 'Menlo'
  palette:
    primary: 'red'
    accent: 'red'
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

extra_css:
 - 'stylesheets/extra.css'
  
plugins:
  - markdownextradata: # используется для подстановки переменных в текст на этапе препроцессинга
      data: variables  # путь относительно корня к каталогу, где лежат yml или json файлы с переменными для подстановки 
  - search

markdown_extensions:
  - codehilite
  - markdown_include.include:
      base_path: docs
  - attr_list

extra:
  disqus: 